package org.dyndns.merelin.pchrc.server.service;

public enum Function {
    // setting
    LIST_LANGUAGE("list_language"),
    SET_LANGUAGE("set_language"),
    GET_LANGUAGE("get_language"),
    LIST_SUBTITLE_LANGUAGE("list_subtitle_language"),
    SET_SUBTITLE_LANGUAGE("set_subtitle_language"),
    GET_SUBTITLE_LANGUAGE("get_subtitle_language"),
    LIST_REPEAT_MODE("list_repeat_mode"),
    SET_REPEAT_MODE("set_repeat_mode"),
    GET_REPEAT_MODE("get_repeat_mode"),
    LIST_SLIDE_SHOW_EFFECT("list_slide_show_effect"),
    SET_SLIDE_SHOW_EFFECT("set_slide_show_effect"),
    GET_SLIDE_SHOW_EFFECT("get_slide_show_effect"),
    LIST_PHOTO_INTERVAL("list_photo_interval"),
    SET_PHOTO_INTERVAL("set_photo_interval"),
    GET_PHOTO_INTERVAL("get_photo_interval"),
    LIST_SCREEN_SAVER_TIME("list_screen_saver_time"),
    SET_SCREEN_SAVER_TIME("set_screen_saver_time"),
    GET_SCREEN_SAVER_TIME("get_screen_saver_time"),
    SET_SETUP_PAGE_LOCK("set_setup_page_lock"),
    GET_SETUP_PAGE_LOCK("get_setup_page_lock"),
    LIST_VIDEO_OUTPUT("list_video_output"),
    SET_VIDEO_OUTPUT("set_video_output"),
    GET_VIDEO_OUTPUT("get_video_output"),
    LIST_FRAMERATE_SYNC("list_framerate_sync"),
    SET_FRAMERATE_SYNC("set_framerate_sync"),
    GET_FRAMERATE_SYNC("get_framerate_sync"),
    LIST_VIDEO_ZOOM("list_video_zoom"),
    SET_VIDEO_ZOOM("set_video_zoom"),
    GET_VIDEO_ZOOM("get_video_zoom"),
    LIST_TV_TYPE("list_tv_type"),
    SET_TV_TYPE("set_tv_type"),
    GET_TV_TYPE("get_tv_type"),
    LIST_COLOR_SPACE("list_color_space"),
    SET_COLOR_SPACE("set_color_space"),
    GET_COLOR_SPACE("get_color_space"),
    SET_HDMI_AUDIO("set_hdmi_audio"),
    GET_HDMI_AUDIO("get_hdmi_audio"),
    LIST_SURROUND_MODE("list_surround_mode"),
    SET_SURROUND_MODE("set_surround_mode"),
    GET_SURROUND_MODE("get_surround_mode"),
    LIST_DTS_AUDIO_MODE("list_dts_audio_mode"),
    SET_DTS_AUDIO_MODE("set_dts_audio_mode"),
    GET_DTS_AUDIO_MODE("get_dts_audio_mode"),
    LIST_AC3_AUDIO_MODE("list_ac3_audio_mode"),
    SET_AC3_AUDIO_MODE("set_ac3_audio_mode"),
    GET_AC3_AUDIO_MODE("get_ac3_audio_mode"),
    LIST_AAC_AUDIO_MODE("list_aac_audio_mode"),
    SET_AAC_AUDIO_MODE("set_aac_audio_mode"),
    GET_AAC_AUDIO_MODE("get_aac_audio_mode"),
    LIST_WMA_PRO_AUDIO_MODE("list_wma_pro_audio_mode"),
    SET_WMA_PRO_AUDIO_MODE("set_wma_pro_audio_mode"),
    GET_WMA_PRO_AUDIO_MODE("get_wma_pro_audio_mode"),
    LIST_PCM_AUDIO_MODE("list_pcm_audio_mode"),
    SET_PCM_AUDIO_MODE("set_pcm_audio_mode"),
    GET_PCM_AUDIO_MODE("get_pcm_audio_mode"),
    LIST_NETWORK_MODE("list_network_mode"),
    SET_NETWORK_MODE("set_network_mode"),
    GET_NETWORK_MODE("get_network_mode"),
    LIST_TIME_ZONE("list_time_zone"),
    SET_TIME_ZONE("set_time_zone"),
    GET_TIME_ZONE("get_time_zone"),
    SET_TIME_SERVER("set_time_server"),
    GET_TIME_SERVER("get_time_server"),
    SET_DAYLIGHT_SAVING("set_daylight_saving"),
    GET_DAYLIGHT_SAVING("get_daylight_saving"),
    SET_IP_SETTING("set_ip_setting"),
    GET_IP_SETTING("get_ip_setting"),
    LIST_NETWORK_SHARED_FOLDER("list_network_shared_folder"),
    ADD_NETWORK_SHARED_FOLDER("add_network_shared_folder"),
    DELETE_NETWORK_SHARED_FOLDER("delete_network_shared_folder"),
    LIST_DVD_PARENTAL_CONTROL_LEVEL("list_dvd_parental_control_level"),
    SET_DVD_PARENTAL_CONTROL_LEVEL("set_dvd_parental_control_level"),
    GET_DVD_PARENTAL_CONTROL_LEVEL("get_dvd_parental_control_level"),
    SET_DVD_CDDA_AUTOPLAY("set_dvd_cdda_autoplay"),
    GET_DVD_CDDA_AUTOPLAY("get_dvd_cdda_autoplay"),
    LIST_DVD_AUDIO_LANGUAGE("list_dvd_audio_language"),
    SET_DVD_AUDIO_LANGUAGE("set_dvd_audio_language"),
    GET_DVD_AUDIO_LANGUAGE("get_dvd_audio_language"),
    LIST_DVD_SUBTITLE_LANGUAGE("list_dvd_subtitle_language"),
    SET_DVD_SUBTITLE_LANGUAGE("set_dvd_subtitle_language"),
    GET_DVD_SUBTITLE_LANGUAGE("get_dvd_subtitle_language"),
    SET_DVD_PARENTAL_CONTROL_PASSWORD("set_dvd_parental_control_password"),
    SET_PROXY_SETTING("set_proxy_setting"),
    GET_PROXY_SETTING("get_proxy_setting"),
    LIST_WIRELESS_SSID("list_wireless_ssid"),
    LIST_WIRELESS_CONNECTION("list_wireless_connection"),
    LIST_WIRELESS_SECURITY("list_wireless_security"),
    GET_WIRELESS_SSID("get_wireless_ssid"),
    GET_WIRELESS_CONNECTION("get_wireless_connection"),
    GET_WIRELESS_SECURITY("get_wireless_security"),
    SET_WIRELESS_SSID("set_wireless_ssid"),
    SET_WIRELESS_CONNECTION("set_wireless_connection"),
    SET_WIRELESS_SECURITY("set_wireless_security"),
    SET_WIRELESS_SETTING("set_wireless_setting"),
    LIST_FILE_LOCK("list_file_lock"),
    SET_FILE_LOCK("set_file_lock"),
    GET_FILE_LOCK("get_file_lock"),
    LIST_SETUP_OPTION("list_setup_option"),
    LIST_BD_NAVIGATION_OPTION("list_bd_navigation_option"),
    SET_BD_NAVIGATION("set_bd_navigation"),
    GET_BD_NAVIGATION("get_bd_navigation"),
    LIST_DRC_OPTION("list_drc_option"),
    SET_DRC("set_drc"),
    GET_DRC("get_drc"),
    LIST_CONNECTION_SPEED_OPTION("list_connection_speed_option"),
    SET_CONNECTION_SPEED("set_connection_speed"),
    GET_CONNECTION_SPEED("get_connection_speed"),
    LIST_DNS_ADDRESS_SETUP("list_dns_address_setup"),
    SET_DNS_ADDRESS_SETUP("set_dns_address_setup"),
    GET_DNS_ADDRESS_SETUP("get_dns_address_setup"),
    SET_DNS_ADDRESS("set_dns_address"),
    GET_DNS_ADDRESS("get_dns_address"),
    GET_PREFERENCES("get_preferences"),
    GET_AUDIO("get_audio"),
    GET_VIDEO("get_video"),
    GET_DVD("get_dvd"),
    GET_SECURITY("get_security"),
    GET_MAINTENANCE("get_maintenance"),
    GET_NMT_APPLICATION("get_nmt_application"),
    GET_CONFIGURE_IP("get_configure_ip"),
    GET_WIRELESS_CONFIG("get_wireless_config"),
    GET_ADVANCED_NETWORK("get_advanced_network"),
    SET_SCANNER_LANGUAGE("set_scanner_language"),
    GET_SCANNER_LANGUAGE("get_scanner_language"),
    SET_MENU_MODE("set_menu_mode"),
    GET_MENU_MODE("get_menu_mode"),
    SET_RECENT_ACTIVITY("set_recent_activity"),
    GET_RECENT_ACTIVITY("get_recent_activity"),
    SET_BROWSE_MODE("set_browse_mode"),
    GET_BROWSE_MODE("get_browse_mode"),
    SET_WALLPAPER_DOWNLOAD_OPTION("set_wallpaper_download_option"),
    GET_WALLPAPER_DOWNLOAD_OPTION("get_wallpaper_download_option"),

    // playback
    LIST_VOD_SUPPORTED_FORMAT("list_vod_supported_format"),
    NEXT_DVD("next_dvd"),
    PREVIOUS_DVD("previous_dvd"),
    MENU_DVD("menu_dvd"),
    TITLE_DVD("title_dvd"),
    START_VOD("start_vod"),
    GET_CURRENT_VOD_INFO("get_current_vod_info"),
    LIST_PLAYBACK_SPEED_VOD("list_playback_speed_vod"),
    GET_PLAYBACK_SPEED_VOD("get_playback_speed_vod"),
    SET_PLAYBACK_SPEED_VOD("set_playback_speed_vod"),
    STEP_VOD("step_vod"),
    REPEAT_VOD("repeat_vod"),
    LIST_SUBTITLE_VOD("list_subtitle_vod"),
    SET_SUBTITLE_VOD("set_subtitle_vod"),
    LIST_AUDIO_VOD("list_audio_vod"),
    SET_AUDIO_VOD("set_audio_vod"),
    SET_TIME_SEEK_VOD("set_time_seek_vod"),
    SET_ZOOM_VOD("set_zoom_vod"),
    PAUSE_VOD("pause_vod"),
    RESUME_VOD("resume_vod"),
    STOP_VOS("stop_vod"),
    INSERT_VOD_QUEUE("insert_vod_queue"),
    NEXT_VOD_IN_QUEUE("next_vod_in_queue"),
    DELETE_VOD_ENTRY_QUEUE("delete_vod_entry_queue"),
    LIST_VOD_QUEUE_INFO("list_vod_queue_info"),
    LIST_AOD_SUPPORTED_FORMAT("list_aod_supported_format"),
    START_AOD("start_aod"),
    GET_CURRENT_AOD_INFO("get_current_aod_info"),
    PAUSE_AOD("pause_aod"),
    RESUME_AOD("resume_aod"),
    REPEAT_AOD("repeat_aod"),
    STOP_AOD("stop_aod"),
    INSERT_AOD_QUEUE("insert_aod_queue"),
    NEXT_AOD_IN_QUEUE("next_aod_in_queue"),
    DELETE_AOD_ENTRY_QUEUE("delete_aod_entry_queue"),
    LIST_AOD_QUEUE_INFO("list_aod_queue_info"),
    LIST_POD_SUPPORTED_FORMAT("list_pod_supported_format"),
    MARQUEE_AOD("marquee_aod"),
    START_POD("start_pod"),
    GET_CURRENT_POD_INFO("get_current_pod_info"),
    PAUSE_POD("pause_pod"),
    RESUME_POD("resume_pod"),
    SET_ZOOM_POD("set_zoom_pod"),
    STOP_POD("stop_pod"),
    INSERT_POD_QUEUE("insert_pod_queue"),
    NEXT_POD_IN_QUEUE("next_pod_in_queue"),
    DELETE_POD_ENTRY_QUEUE("delete_pod_entry_queue"),
    LIST_POD_QUEUE_INFO("list_pod_queue_info"),
    PREV_PLAYLIST_AOD_IN_QUEUE("prev_playlist_aod_in_queue"),
    NEXT_PLAYLIST_AOD_IN_QUEUE("next_playlist_aod_in_queue"),
    START_DATABASE_AOD("start_database_aod"),
    INSERT_DATABASE_AOD_QUEUE("insert_database_aod_queue"),
    DELETE_PLAYLIST_AOD_QUEUE("delete_playlist_aod_queue"),
    LIST_PLAYLIST_AOD_QUEUE_INFO("list_playlist_aod_queue_info"),
    GET_PLAYLIST_CURRENT_AOD_INFO("get_playlist_current_aod_info"),
    PREV_AOD_IN_QUEUE("prev_aod_in_queue"),
    START_DATABASE_VOD("start_database_vod"),
    NEXT_DATABASE_VOD_IN_QUEUE("next_database_vod_in_queue"),
    PREV_DATABASE_VOD_IN_QUEUE("prev_database_vod_in_queue"),
    STOP_DATABASE_VOD("stop_database_vod"),
    START_DATABASE_POD("start_database_pod"),

    // file_operation
    LIST_USER_STORAGE_FILE("list_user_storage_file"),

    // network_browse
    LIST_NETWORK_RESOURCE("list_network_resource");

    private final String name;

    Function(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public static Function getFunction(String name) {
        if (name != null) {
            for (Function f : Function.values()) {
                if (f.name.equals(name)) {
                    return f;
                }
            }
        }

        throw new IllegalArgumentException("Unknown function name: " + name);
    }
}
